### ISSUE TITLE
Some messages can crash tmda-rfilter

### ISSUE THREAD

**Issue by KevinGoodsell** [KevinGoodsell/tmda-fork#7]
This traceback has been reported several times over the years on the tmda mailing lists:

```
Traceback (most recent call last):
  File "/usr/bin/tmda-filter", line 53, in ?
    execfile(os.path.join(execdir, 'tmda-rfilter'))
  File "/usr/bin/tmda-rfilter", line 213, in ?
    orig_msgin_as_string = Util.msg_as_string(msgin)
  File "/usr/local/src/tmda-1.1.12/TMDA/Util.py", line 552, in msg_as_string
    g.flatten(msg, unixfrom=unixfrom)
  File "/usr/local/src/tmda-1.1.12/TMDA/pythonlib/email/generator.py", line 84, in flatten
    self._write(msg)
  File "/usr/local/src/tmda-1.1.12/TMDA/pythonlib/email/generator.py", line 109, in _write
    self._dispatch(msg)
  File "/usr/local/src/tmda-1.1.12/TMDA/pythonlib/email/generator.py", line 135, in _dispatch
    meth(msg)
  File "/usr/local/src/tmda-1.1.12/TMDA/pythonlib/email/generator.py", line 266, in _handle_message
    g.flatten(msg.get_payload(0), unixfrom=False)
  File "/usr/local/src/tmda-1.1.12/TMDA/pythonlib/email/message.py", line 185, in get_payload
 raise TypeError('Expected list, got %s' % type(self._payload))
TypeError: Expected list, got <type 'str'> 
```

This is due to a mis-handling of messages that are parsed with HeaderParser. Messages with Content-type: message/&lt;anything&gt; are assumed by Generator to have list payloads, but HeaderParser always creates string payloads (the unparsed body).

In the original TMDA subversion there is a hacky fix in rev 1673, which was apparently broken in rev 2050, and removed in rev 2083 (though there are still some remnants), in the hope that the email package had fixed the problem. It hadn't.

Recently a fix was put into the Python library:

http://bugs.python.org/issue7970

A work-around for earlier Python versions will probably take the form of a Generator-derived class that overrides _handle_message to make it look like the fixed version.

**Comment by KevinGoodsell** [comment]
This issue is fixed in any recent Python version, but persists in upstream TMDA due to the outdated pythonlib/email module that overrides the built-in version. The solution will probably be to remove pythonlib.

**Comment by KevinGoodsell** [comment]
pythonlib has now been removed upstream. Since this issue is essentially a Python library issue which has now been fixed for some time, no work-around is necessary in TMDA. Closing.
